### ISSUE TITLE
Older version of package is seen by yay

### ISSUE THREAD

**Issue by mxmilkb** [localnet/aurci#12]
![rose_2019-11-28-06:07:02](https://user-images.githubusercontent.com/108225/69781246-6d584980-11a5-11ea-8bb5-9c3ec6f64487.png)

**Comment by localnet** [comment]
Can you try:
1) Resync packages and check that there are no errors, few times, but sometimes can fail (network errors of GH?).
2) Try using `pacman` to discard a possible trouble with `yay` (I never used it). 
3) If all this fail, possibly there is `aurutils` upstream bug because is it who update database after it build the packages.

**Comment by localnet** [comment]
Seems a trouble with sync or with `yay` because the GH database seems contain the correct version:

```bash
$ tar tf aur-av-bin.db.tar.gz | grep element
element-git-0.42.0_rc1.r75.gd10584cc-1/
element-git-0.42.0_rc1.r75.gd10584cc-1/desc
```

```
$ tar tf aur-av-bin.db | grep element
element-git-0.42.0_rc1.r75.gd10584cc-1/
element-git-0.42.0_rc1.r75.gd10584cc-1/desc
```

```
$ tar tf aur-av-bin.files.tar.gz | grep element
element-git-0.42.0_rc1.r75.gd10584cc-1/
element-git-0.42.0_rc1.r75.gd10584cc-1/files
element-git-0.42.0_rc1.r75.gd10584cc-1/desc
```

```
tar tf aur-av-bin.files | grep element
element-git-0.42.0_rc1.r75.gd10584cc-1/
element-git-0.42.0_rc1.r75.gd10584cc-1/files
element-git-0.42.0_rc1.r75.gd10584cc-1/desc
```

**Comment by redtide** [comment]
I use `yay` as well. I think it may be a `$HOME/.cache/yay` issue but not sure, I don't remember to had such problem in the past.

**Comment by mxmilkb** [comment]
I think this was my mistake as I had not updated the renamed repo name (only the url) in pacman.conf.
