### ISSUE TITLE
Custom makepkg.conf: PACKAGER, CFLAGS & friends

### ISSUE THREAD

**Issue by redtide** [localnet/aurci#18]
I'm trying to implement this but I have some trouble to make it work and stop that warning, that it seems to persist also in my system and IDK why he's not happy with the one I have.
Other than that I'm not sure if it's OK to have it in the `pkguser` [home] or [globally] in etc, although I tried the latter already and gave me some errors.

[home]: https://travis-ci.com/redtide/redtide-aur/builds/139014770
[globally]: https://travis-ci.com/redtide/redtide-aur/builds/139015800

**Comment by localnet** [comment]
[ArchWiki](https://wiki.archlinux.org/index.php/Makepkg):
>The system configuration is available in /etc/makepkg.conf, but user-specific changes can be made in $XDG_CONFIG_HOME/pacman/makepkg.conf or ~/.makepkg.conf.

- If `/etc/makepkg.conf` is used I don't sure if is always required to specify `CFLAGS`, etc.
- if `$XDG_CONFIG_HOME/pacman/makepkg.conf` is used I don't sure if `$XDG_CONFIG_HOME` is defined by default in the Docker image.

So, to define only some variables as `PACKAGER`, I think the best election is `~/.makepkg.conf`.

I like the current definition of `PACKAGER` because it permit use of environment variables to add a URL with the Travis-CI build log.

I don't know if we can change `export PACKAGER="https://travis-ci.org/${1}/builds/${2}"` by, for example, `export PACKAGER="${2} https://travis-ci.org/${1}/builds/${2} travis@ci.invalid"` to remove the warning. And if somebody define `PACKAGER` in `makepkg.conf` I'm not sure which one of them would have preference.

**Comment by redtide** [comment]
up to a certain point my `$ HOME / .config / pacman / makepkg.conf` always worked for my AUR packages, at least I saw it displayed correctly in the package information (I don't remember if it was on Pamac or else), seems to be a problem with `makepkg`, I need to investigate.

I don't remember that it even worked directly from `$HOME`, perhaps because I don't like having many dotfiles in there, so I agree that it would simplify things, I'll implement it.

From my POV the PACKAGER setting should be set in its makepkg.conf, hardcoding it, even if using some globs like pattern in the aurci configuration, seems to me limiting and also requires people to modify it there if they want to use their own, one-place-for-all-settings would be better and also native in this case.

**Comment by redtide** [comment]
BTW it seems to work anyway:
```bash
$ pacman -Qi smarthhc 
Nome                      : smarthhc
Versione                  : r94.2cfd792-1
Descrizione               : Digital HiHat Controller
Architettura              : x86_64
...
Pacchettizzatore          : https://travis-ci.com/redtide/redtide-aur/builds/138396486
Data di creazione         : mer 27 nov 2019, 18:11:35
Data di installazione     : mer 27 nov 2019, 18:28:07
...
```
so it might be just some harmless, only annoying, warning.

**Comment by redtide** [comment]
Update: it works now with .[makepkg.conf] and the warning vanished: was some missing '>' character before, so I'll send you a PR for this soon, preserving the export in [pkgbuild.sh] if the file is not added by the user in the root, does it sounds OK?
```
# pacman -Qi smarthhc
Nome                      : smarthhc
Versione                  : r94.2cfd792-1
...
Pacchettizzatore          : AURCI Build <travis_bot@email.invalid>
Data di creazione         : mar 3 dic 2019, 05:06:36
Data di installazione     : mar 3 dic 2019, 05:16:15
...
```
[makepkg.conf]: https://github.com/redtide/redtide-aur/blob/custom/makepkg.conf
[pkgbuild.sh]: https://github.com/redtide/redtide-aur/blob/custom/pkgbuild.sh

**Comment by localnet** [comment]
> up to a certain point my $HOME/.config/pacman/makepkg.conf always worked for my AUR packages, at least I saw it displayed correctly in the package information (I don't remember if it was on Pamac or else), seems to be a problem with makepkg, I need to investigate.

But surely you have install `xdg-user-dirs` as dependency of your desktop.

> I don't remember that it even worked directly from $HOME, perhaps because I don't like having many dotfiles in there, so I agree that it would simplify things, I'll implement it.

I am agree, but this is a Docker container created for a single purpose and destroyed after.

> I'll send then you a PR for this soon, preserving the export in pkgbuild.sh if the file is not added by the user in the repo root: does this sounds OK?

Can you try to simply to add the `.makepkg.conf`? I think it might overwrite the export in pkgbuild.sh and work.

If this "if - else" is not necessary everything will be easier (If it is required too will be required in `.travis.yml` at least):
```
if [ ! -f "/home/pkguser/.makepkg.conf" ]; then
  echo "No makepkg.conf found, exporting PACKAGER variable."
  export PACKAGER="https://travis-ci.com/${1}/builds/${2}"
else
  echo "/home/pkguser/.makepkg.conf found, ensure that the PACKAGER variable is set there."
fi
```

> Just suggest me which variable to set in pkgbuild.sh: it's fine to me as is (except change the .org to .com) even with the warning, otherwise it results too long: it tells already where to find the build for the package.

> Otherwise it could be something like:
redtide redtide-aur <138396486@travis.build.id>

I like your proposal `<138396486@travis.build.id>` seems enough information.

**Comment by redtide** [comment]
That's fine, I'll try now without if - else adding also the new "fake email".

**Comment by redtide** [comment]
It uses always the one exported even with makepkg.conf copied.
Other than that I don't see why not using the if - else since it also warns that, having the conf file, the PACKAGER variable should already be there or it will not exists.

[without the makepkg]:
```
# pacman -Qi realtime-generic-setup
Nome                      : realtime-generic-setup
...
Pacchettizzatore          : redtide redtide-aur <139208686@.build.id>
Data di creazione         : mar 3 dic 2019, 20:48:47
...
```
same [with the makepkg]:
```
# pacman -Qi realtime-generic-setup
Nome                      : realtime-generic-setup
...
Pacchettizzatore          : redtide redtide-aur <139211538@.build.id>
Data di creazione         : mar 3 dic 2019, 21:08:07
```
[without the makepkg]: https://travis-ci.com/redtide/redtide-aur/builds/139208686#L501
[with the makepkg]: https://travis-ci.com/redtide/redtide-aur/builds/139211538#L501
