### ISSUE TITLE
removed packages

### ISSUE THREAD

**Issue by cromerc** [localnet/aurci#2]
Packages removed from the pkglist are not removed from the repo.

**Comment by localnet** [comment]
It is not fully tested but they should be removed from repository database (aurci.db.tar.gz) but not from GitHub releases.

For example in your build #24 you can see:

```
+ repo-remove aurci.db.tar.gz acroread
==> Extracting database to a temporary location...
==> Extracting database to a temporary location...
==> Searching for package 'acroread'...
  -> Removing existing entry 'acroread-9.5.5-6'...
==> Creating updated database file 'aurci.db.tar.gz'
==> WARNING: No packages remain, creating empty database.
==> WARNING: No packages remain, creating empty database.
```

I don't know if maintain GitHub release as a history of all built packages (you can remove it manually) or implement this feature.

**Comment by cromerc** [comment]
Going to close this.
