### ISSUE TITLE
Dependency version issue

### ISSUE THREAD

**Issue by mxmilkb** [localnet/aurci#27]
Trying to build [lilv-git](https://aur.archlinux.org/packages/lilv-git/). I've got lv2-git [being built](https://github.com/mxmilkb/aur-av-bin/blob/master/pkglist#L3) but lilv-git [fails](https://travis-ci.com/mxmilkb/aur-av-bin/builds/141449759#L11720) with "Checking for 'lv2 >= 1.17.0'                  : not found.

**Comment by localnet** [comment]
I will try see it with time. But [this](https://aur.archlinux.org/packages/lv2-git/) seems 1.16.2.r1189.49777ff-1 so less than 1.17.0.

**Comment by mxmilkb** [comment]
That's the pkg variable in the AUR entry PKGBUILD. If cloned and built;
```
...
==> Starting pkgver()...
==> Updated version: lv2-git 1.17.0.r1192.06d3f56-1
...
```

**Comment by localnet** [comment]
Ok. [lilv-git](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lilv-git): `depends=('lv2' 'python' 'sratom')` so it don't explicitly specifies lv2-git, it say lv2 is valid and enough (if I understand it correctly).

Although you add `lv2-git` to the build list, it is only [build](https://travis-ci.com/mxmilkb/aur-av-bin/builds/141449759#L11662), not installation. And `lv2` does seem to be [installed](https://travis-ci.com/mxmilkb/aur-av-bin/builds/141449759#L9930) previously as dependency of `sratom` (if I understand it correctly).

If you will go to use "git packages", very often, then should learn to debug these things by yourself.

**Comment by mxmilkb** [comment]
I was getting confused between ingen-git PKGBUILD and lilv-git PKGBUILD. The lilv-git PKGBUILD doesn't not specify an lv2-git version, though it was the lilv build that failed because of this.

**Comment by mxmilkb** [comment]
Let it be put this way; `yay` would not fail if given the AUR entries in pkglist.

I spoke to SpotlightKid/strogon14 on IRC, they have kindly now updated the pkgver variable information for both the lv2-git and lilv-git entries on the AUR, i.e. the lilv-git AUR entry now reports as depending on `lv2>=1.17.0 (lv2-git)`, lv2-git in AUR is 1.17+, and community/lv2 is 1.16.0-3, so the problem should not be in the PKGBUILD level of things.

The second statement/paragraph, now the third, about lv2-git being built was a vague seed of a suggestion toward bootstrapping the build environment with the packages available from the generated repository. It might require two turns of the wheel though.. or maybe another solution could make this edge case work.

Anyhway, I thank you for your work on this project :)

**Comment by localnet** [comment]
I'm not sure if I understand you well, it is difficult to me understand and express myself in english well (excuse me if sometimes I sound rude)

Now with the right PKGBUILD (`lilv-git`: `lv2>=1.17.0` and `lv2-git 1.17+` in AUR) adding both packages to `pkglist` all seems work well:

https://travis-ci.com/localnet/aurci/builds/141689779

With `lilv-git` only in pkglist it fail:

https://travis-ci.com/localnet/aurci/builds/141690031

Are you saying that with `yay` if the package exists in official repositories but it is wrong version, then it search a package in AUR providing `lv2>=1.17.0`?

**Comment by mxmilkb** [comment]
Hmm, the build is working now, I guess I was mistaken about some part of the process. Thanks for the assistance though!
