### ISSUE TITLE
Failure on packages with pgp keys

### ISSUE THREAD

**Issue by cromerc** [localnet/aurci#3]
Packages that use pgp keys to sign the source code fail since the key is not in the keyring.
An example of this can be seen with the AUR package "cower".

**Comment by localnet** [comment]
Can you try now? Adding GPG key (1EB2638FF56C0C53) to "pkgkeys" archive (one by line).

**Comment by cromerc** [comment]
I will give it a try after I get home from the uni. But I can already see a problem with the code. What happens if the pgp is not in the mit server. For example my key that I use to sign files is not in the mit server. My key is in https://sks-keyservers.net so my packages would fail with this fix.

**Comment by localnet** [comment]
In this [GPG Tutorial](https://futureboy.us/pgp.html#ImportingAKey) it say:
 > all the major keyservers mirror each other, so you could probably get it from the keyserver of your choice

In this case, doing a search by email "d (at) falconindy (dot) com", I can found the key in all tested keyservers:
 - https://pgp.mit.edu
 - https://sks-keyservers.net
 - https://pgp.key-server.io

Can you try it with your key @cromerc?

**Comment by localnet** [comment]
Doing a search by email "chris (at) cromer (dot) cl", too I can found the key in all tested keyservers:

- https://pgp.mit.edu
- https://sks-keyservers.net
- https://pgp.key-server.io

Solved on commit [9f9cb53](https://github.com/localnet/aurci/commit/9f9cb53eaeee3d2156599b2474f904493b1efeaf)
