### ISSUE TITLE
Package conflicts causing a failure

### ISSUE THREAD

**Issue by mxmilkb** [localnet/aurci#5]
`dpf-plugins-git` requires `jack2` and `picard-plugins-git` (`picard`)/`sequencer64-git` requires `jack`.

This gives a `:: jack2 and jack are in conflict. Remove jack? [y/N] error: unresolvable package conflicts detected` in the [log](https://travis-ci.com/mxmilkb/aurci/builds/137702754#L9367).

**Comment by localnet** [comment]
The trouble is here:
```
:: jack2 and jack are in conflict. Remove jack? [y/N]
```

Both "pacman --noconfirm" and "aur sync -n" always select the default option, at this case "N".

Possible solutions:
1) Force always "yes" as response. I not sure if this can break something, now I can't think of any message where the correct response can be "no".

2) I didn't tested it, but I think it can work. Create another file with pacman packages to install before that AUR packages to be installed. In this case if `jack2` is installed before to `sequencer64-git`, I think will not install `jack`. But this solution require more user interaction and analysis...

what do you think is better?

**Comment by mxmilkb** [comment]
Ah, it turns out `dpf-plugins-git` is at fault here, as `jack` provides jack2. I've requested it to be orphaned so that can get fixed.

Possibly there is a way to cope with such packages. I have tried `echo y | yay ...` before, and that works in 90% of instances, but there are times when a package is replaced in the repos and the user has to select a number. Maybe `pacman` is more forgiving in that way though..

Anyway, not a blocking issue for me now, thanks for the time, feel free to close if this is too much of an edge case :)

**Comment by localnet** [comment]
I'll leave it open for now and will try to get some of time to rethink it.

**Comment by redtide** [comment]
I think the better thing should be either, like in this case, to fix the package (author responsibility) or choose another one in the pkglist, like to create a own package version if the former option cannot be satisfied; you cannot predict in which case could be a better choice and default choices are there for this purpose.
