### ISSUE TITLE
Building official packages?

### ISSUE THREAD

**Issue by mxmilkb** [localnet/aurci#7]
Through entering, say, `community/carla` in the pkglist?

**Comment by redtide** [comment]
Official packages are already distributed as package, what could be the benefit by doing it here in an AUR context?

**Comment by localnet** [comment]
I agree, can you expose a right motivation?

**Comment by mxmilkb** [comment]
My use case was for testing.

A general use case would be if someone wished to have an Arch or Arch derivative system that only has access to a subset of the packages in the official repos without needing to have access to all the other packages.

I don't particularly need that setup myself, but I'll leave it up to you to close or not depending on what you might want to do.

**Comment by redtide** [comment]
I have some difficulty to imagine that use case since if you can access to GH to download your own AUR packages you should have also access to an official repo. I think instead about the possibility to create some unofficial mirror but I have no experience/knowledge about it, I can only suppose it has some different approach? In this case I think we should ask to some expert we both know :)

**Comment by mxmilkb** [comment]
Sometimes constraints can be advantageous. Maybe someone might have a need for a limited repo (or a limited official repo but with some AUR binaries also), and this feature would allow that to exist easier than a self-hosting route. Maybe a teaching environment, like a computer lab setup, or a "my first Arch Linux derivative" restricted environment to not overwhelm kids. Or this could totally be out of scope of the project, in which case just close this off, all cool :) Maybe someday someone will actually want it and comment and it'd be worth the effort.

**Comment by redtide** [comment]
OK, so basically this is a feature request to being able to build packages to provide a hybrid repository with both AUR and official ([ABS]?) packages for some custom system, like it could be by using [archiso] with the `releng` configuration to build an Arch ISO image with custom packages (both official and from AUR).

[ABS]: https://wiki.archlinux.org/index.php/Arch_Build_System
[archiso]: https://wiki.archlinux.org/index.php/Archiso#Custom_local_repository

**Comment by localnet** [comment]
Initially, this feature is out out of scope of the project, that internally use `aurutils` and I don't see it support ABS.

If somebody in the future is interested to use it, I could go back to think if implement it. The more easy approach can be download the packages add they to the repository database and deploy they to GH without need to build they.
