### ISSUE TITLE
Make the repo more "user-forkable"

### ISSUE THREAD

**Issue by redtide** [localnet/aurci#8]
I would like to know if you could agree by changing the README to point to some GitHub pages for instructions: [GitHub doesn't support variable substitution in README], but you can do it in `gh-pages` so you don't have to "hardcode" your own travis-ci project budge link so that people forking it will use yours and not theirs.
This way could be a workaround it and make automatically the substitution in the forked ones, so they shouldn't even change it.
I can do this for you as another PR, just let me know. In this case if localnet is a user account and not an organization you can just add a gh-pages branch and I'll do the rest.

[GitHub doesn't support variable substitution in README]: https://stackoverflow.com/questions/18673694/referencing-current-branch-in-github-readme-md

**Comment by localnet** [comment]
Yeah, variable substitution in README would be great. If it is possible a workaround using `gh-pages`, I am agree.

I am added a `gh-pages` branch, localnet is a user account.

**Comment by redtide** [comment]
Cool, now I see another problem: can we get rid of the pkglist, so delete it and add it to .gitignore so people don't have to make changes to your original one?
I wonder if in this case you will need some fork somewhere else of your own repo as a personal repo.

**Comment by localnet** [comment]
How you see this approach?

1) `master` branch with `pkglist` added to `.gitignore` or with a empty `pkglist`.
2) `custom` or `personal` branch without `pkglist` added to `.gitignore` or with data in `pkglist`.
3) Modify `.travis.yml` to only deploy `custom` or `personal` branch:
```
deploy:
  ...
  on:
    branch: custom
```

**Comment by redtide** [comment]
When an user forks a repo it gets also its branches, so I suppose we need an empty pkglist, since it must be checked out by Travis, so not to add it to .gitignore, just remove your custom ones from it (some "template upstream repository", there is also a template repo option in GH setting, not sure if it could also used in this case).
So in your case you would have both the original repo as upstream and also a fork as any other user with his own configuration.

**Comment by localnet** [comment]
If you think it make the repository more "user-forkable" I don't have trouble to see how I can fork my own repository.

After a quick read of [GitHub templates](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template), I am not sure if after convert the repository to template and do new commits the "template-forks" can incorporate this new changes

**Comment by localnet** [comment]
Currently only `master` branch is deployed. If the idea is that the `forks` don't touch the `master` branch, then we need set a branch as default to deploy or the `forks` always will require edit `.travis.yml` to specify a branch to deploy.

**Comment by redtide** [comment]
I'm a bit confused right now but I think that's correct, so use the master as base and changes for deployment on another branch.

**Comment by localnet** [comment]
I will need revise it, but the repositories are migrated already.

**Comment by redtide** [comment]
About the "**NOTE:** List of currently maintained packages can change at any moment." is it referred to your custom list? In this case I think I should remove it, right?

**Comment by localnet** [comment]
Yes, I am referring to my custom list. Maybe leave a note about: if it not your fork don't use it. Create your own forking to use it.

Tanks you, I will try to review tomorrow.

**Comment by redtide** [comment]
Great, thank you. About the list I thought we were about to make it empty in master repo. About the deploy issue I'm not sure how GH Releases works, I need to take a look at Travis docs.

**Comment by redtide** [comment]
It seems that variable option could be the right one, I'm just trying now after:
- reforked the repo
- switched to a new `personal` branch
- set the pkglist
- added a DEPLOY_BRANCH Travis visible variable with `personal` as value
- replaced the `master` value in .travis.yml with `$DEPLOY_BRANCH`

**Comment by redtide** [comment]
Any clue?
About the makepkg's PACKAGER variable I thought:
- to use some [git config setting]
- add a `makepkg.conf` file to copy in $HOME/.config with some default value to let users set it later in their fork together with other makepkg settings (someone asked me if you support also to set custom CFLAGS in it...)

[git config setting]: https://github.com/jonschlinkert/git-user-name/blob/master/.travis.yml

**Comment by localnet** [comment]
Sorry for the late response, time troubles...

> I see also in .travis.yml that aurci is hardcoded, it could be a variable containing the name of the project (I know it's fine as is but I wonder if it could be better to use the forked user project name).

The only difference would be cosmetic, so I don't have real opinion about.

> What do you think? I can setup a PR with the related changes also in the documentation (and make some link from the gh-pages back to the project).

I think it do not complicate the use for somebody without much knowledge so I am agree. I want keep the biggest possible ease of use for everybody.

**Comment by localnet** [comment]
> Any clue?
> About the makepkg's PACKAGER variable I thought:
> 
> * to use some [git config setting](https://github.com/jonschlinkert/git-user-name/blob/master/.travis.yml)
> * add a `makepkg.conf` file to copy in `$HOME/.config/pacman/` with some default value to let users set it later in their fork together with other makepkg settings (someone asked me if you support also to set custom CFLAGS in it...)

I think it is better treat this in another issue.

I have to check it, but I think remember that `aurutils` accepts the use of a `makepkg.conf`, so this approach seems me te better because it permit more posibilities as you say (CFLAGS, etc).

**Comment by redtide** [comment]
> Sorry for the late response, time troubles... Thanks for the research and the work.

np.
> The only difference would be cosmetic, so I don't have real opinion about.

yes, I agree.
> I think it do not complicate the use for somebody without much knowledge so I am agree. I want keep the biggest possible ease of use for everybody.

let me know about the PR.
> I think it is better treat this in another issue.

I think I'll send directly another PR later.
